file:
  upload-directory: /home/green/download
  profile-pic: profile

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: true
        strategy: refresh
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.93/pih
    username: pih
    password: green502
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
