server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

  application:
    name: otd_life
  jackson:
    time-zone: Asia/Seoul          # 로컬 시간대 고정(로그/응답 일관성)
  servlet:
    multipart: # 파일 업로드(커뮤니티 첨부파일용)
      max-file-size: 15MB
      max-request-size: 30MB
  datasource:
    url: jdbc:log4jdbc:mariadb://112.222.157.157:5012/pih
    username: pih
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    database: mysql
    open-in-view: false            # 영속성 컨텍스트 요청-응답 분리
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      #ddl-auto: create

    properties:
      hibernate:
        jdbc:
          batch_size: 20
        format_sql: true
        order_updates: true
        show_sql: true
        default_batch_fetch_size: 100  # N+1 완화에 도움
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

feign:                              # 서버-투-서버 통신(유저 서비스 등)
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
  compression:
    request:
      enabled: true
    response:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.cloud.openfeign: info   # 필요시 debug로 내리면 상세통신 확인
#    org.springframework.security: TRACE
#    org.springframework.beans.factory.support: DEBUG #빈등록시 실패하는부분확인
#    org.springframework.web: DEBUG

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml


# 커뮤니티 파일 저장 루트(로컬 저장 시) — LocalFileStorageService에서 사용
constants:
  file:
    directory: "D:\\inha\\healthcare\\img\\item"

  comment:
    start-index: 0
    need-for-view-count: 3
