server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

file:
  upload-directory: /home/green/download
  profile-pic: profile

spring:
  application:
    name: otd_life

  jackson:
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 30MB

  datasource:
    url: jdbc:log4jdbc:mariadb://112.222.157.157:5012/pih
    username: pih
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    database: mysql
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
    # ddl-auto: update
    # ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        format_sql: true
        order_updates: true
        show_sql: true
        default_batch_fetch_size: 100

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
  compression:
    request:
      enabled: true
    response:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.cloud.openfeign: info
    # org.springframework.security: TRACE
    # org.springframework.beans.factory.support: DEBUG
    # org.springframework.web: DEBUG

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

constants:
  comment:
    start-index: 0
    need-for-view-count: 3
  feign-client:
    challenge:
      url: http://localhost:8082/api/OTD/challenge
