server:
  port: 0
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: otd_life
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.93/pih
    username: pih
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    database: mysql
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      #ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        format_sql: true
        order_updates: true
        show_sql: true
  sql:
    init:
      mode: always

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml